export interface km056 {
    Archivo: string;
    Disquete: string;
    Molde: string;
    Porc_pigmento: number;
    Num_Cav_th: number;
    Num_Cav_real: number;
    editado_por: string;
    t_supervi:number;
    inyeccion1v: number;
    inyeccion2v: number;
    inyeccion3v: number;
    inyeccion4v: number;
    inyeccion5v: number;
    inyeccion1p: number;
    inyeccion2p: number;
    inyeccion3p: number;
    inyeccion4p: number;
    inyeccion5p: number;
    inyeccion1s: number;
    inyeccion2s: number;
    inyeccion3s: number;
    inyeccion4s: number;
    inyeccion5s: number;
    tiempo_inyeccion: number;
    tiempo_calentamiento: number;

    sostenimiento_mm: number;
    presion_bar1: number;
    presion_bar2: number;
    presion_bar3: number;
    tiempo_seg1: number;
    tiempo_seg2: number;
    tiempo_seg3: number;
    niveles: number;
    cojin_mm: number;
    n_value: number;
    p_value: number;
    s_value1: number;
    s_value2: number;
    s_value3: number;
    v_value1: number;
    v_value2: number;
    carga_niveles: number;
    tiempo_carga: number;
    cojin: number;
    parametros_salida_tiempo_inyeccion: number;
    parametros_salida_tiempo_carga: number;
    tiempo_ciclo: number;
    presion_conmutacion: number;
    indice_viscosidad: number;

    set_zona101: number;
    set_zona102: number;
    set_zona103: number;
    real_zona101: number;
    real_zona102: number;
    real_zona103: number;
    set_temp: number;
    real_temp:number;
    Z1_Set:number;
    Z2_Set:number;
    Z3_Set:number;
    Z4_Set:number;
    Z17_Set:number;
    Z18_Set:number;
    Z19_Set:number;
    Z20_Set:number;

    N_CIRC:number;
    Molde_real_1:number;
    Molde_real_2:number;
    Molde_real_3:number;
    Molde_real_4:number;
    Molde_real_5:number;
    Molde_real_6:number;
    Molde_real_7:number;
    Molde_real_8:number;
    puentes:number;

    vacio_molde: string;
    tiempo_vacio_molde:number;
    nivel_vacio: number;

    etapa_1:number;
    etapa_2:number;
    etapa_repetida_1:number;
    etapa_repetida_2:number;
    f_70: number;
    f_55: number;
    contador_vibraciones: number;
    posicion_molde: string;
    s_2_1: number;
    v_50: number;
    v_35: number;
    v_85: number;
    f_42: number;
    carrera: number;
    corteDeVena: number;
    funcionCorteVenaNoyo: number;
    estampadoSeparacionBebedero: number;
    avanceExpulsorPresion: number;
    tiempoRetardoAvanceConectado : number;
    tiempoRetardoAvanceDesconectado: number;
    supervisionRecorridoDesbloqueo: number;

    f1: number;
    f2: number;
    f3: number;
    fuerzaCierre1: number;
    fuerzaCierre2: number;
    fuerzaCierre3: number;
    fuerzaCierre4: number;
    limiteFuerzaDesplazamiento: number;
    carreraApertura: number;
    carreraApertura2: number;
    carreraApertura3: number;
    n1: number;
    n2: number;
    n3: number;
    s1: number;
    s2: number;
    cerrars1: number;
    cerrars2: number;
    carreraApertura7: number;

    inyeccionRetardado: number;
    posicionHusillo: number;
    velocidadApertura: number;
    ventilacioncarreraApertura: number;
    tiempoVentilacion: number;
    velocidadCierre: number;
    finalPurgarAire: number;
    fuerzaDesplazamiento: number;
    FUNCION_DE_ESTAMPADO: string;
    Inicio_de_fuerza_de_cierre: string;
    
    noyos1: string;
    noyos2: string;
    noyos3: string;
    noyos4: string;
    noyos5: string;
    noyos6: string;
    noyos7: string;
    noyos8: string;
    noyos9: string;
    noyos10: string;

    noyo1_1: string;
    noyo1_2: string;
    noyo1_3: string;
    noyo2_1: string;
    noyo2_2: string;
    noyo2_3: string;
    noyo2_4: string;
    noyo2_5: string;

    expulsorTn: string;
    expulsorP: string;
    expulsorQ: string;

    interruptorDetras: number;
    posicionInt3: number;
    posicionInt2: number;
    posicionInt1: number;
    carreraVibraciones: number; 
    carreraExpulsor: number;

    narizApoyada: number;
    tipoNariz: number;
    diametroNariz: number;
    proceso: number;
    supervCiclo: number;
    tiempoCiclo: number;
    diametroHusillo: number;
    pesoColada: number;
    pesoPieza: number;
    programaRobot: number;

    tiempoTolvaDerecha: number;
    tiempoTolvaIzquierda: number;
    sentidoGiroTolva   : number;
    embutidoRetardado: number;
    revolucionesTolva: number;
    revolucionesHusillo: number;
    tiempoRetardoSupervision   : number;
    presionEmb : number;
    toleranciaPresionEmb: number;
    regulacionPresionEmb: number;
    temperatura: number;
}